In [1]:
import numpy as np

_1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення._

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

_2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення._

In [4]:
matrix = np.zeros((3,3))

In [5]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

_3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення._

In [6]:
matrix = np.random.randint(1, 11, size=(5, 5))

In [7]:
matrix

array([[5, 7, 1, 6, 4],
       [3, 2, 8, 5, 4],
       [4, 2, 6, 2, 5],
       [4, 1, 1, 8, 3],
       [1, 8, 6, 2, 4]])

_4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення._

In [8]:
matrix = np.random.randint(2, size=(4, 4))

In [9]:
matrix

array([[0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0]])

_5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення._

In [10]:
arr_1 = np.random.randint(1, 11, 5)
arr_2 = np.random.randint(1, 11, 5)

In [11]:
arr_1

array([4, 8, 1, 8, 9])

In [12]:
arr_2

array([7, 2, 6, 2, 4])

In [13]:
arr_1 + arr_2

array([11, 10,  7, 10, 13])

In [14]:
arr_1 - arr_2

array([-3,  6, -5,  6,  5])

In [15]:
arr_1 * arr_2

array([28, 16,  6, 16, 36])

_6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток._

In [16]:
arr_1 = np.random.randint(1, 8, 7)
arr_2 = np.random.randint(1, 8, 7)

In [17]:
arr_1

array([6, 3, 6, 5, 5, 3, 4])

In [18]:
arr_2

array([7, 1, 4, 4, 4, 1, 2])

In [19]:
s_dot = np.dot(arr_1, arr_2)

In [20]:
s_dot

120

_7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою._

In [21]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 3))

In [22]:
matrix_1

array([[8, 4],
       [4, 2]])

In [23]:
matrix_2

array([[1, 6, 7],
       [4, 1, 5]])

In [24]:
np.dot(matrix_1, matrix_2)

array([[24, 52, 76],
       [12, 26, 38]])

_8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю._

In [25]:
matrix = np.random.randint(1, 11, size=(3, 3))
matrix

array([[ 9, 10,  5],
       [10,  5,  2],
       [ 3,  6,  7]])

In [26]:
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[-0.11057692,  0.19230769,  0.02403846],
       [ 0.30769231, -0.23076923, -0.15384615],
       [-0.21634615,  0.11538462,  0.26442308]])

In [27]:
inverse_matrix = np.linalg.inv(inverse_matrix)
inverse_matrix

array([[ 9., 10.,  5.],
       [10.,  5.,  2.],
       [ 3.,  6.,  7.]])

_9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її._

In [28]:
matrix = np.random.random((4, 4))
matrix

array([[0.99050059, 0.62412991, 0.98596431, 0.50296935],
       [0.3763948 , 0.69174945, 0.76046633, 0.78574223],
       [0.06454403, 0.15683101, 0.37250486, 0.76119489],
       [0.24445585, 0.13135137, 0.2560899 , 0.57887849]])

In [29]:
transposed_matrix = np.transpose(matrix)
transposed_matrix

array([[0.99050059, 0.3763948 , 0.06454403, 0.24445585],
       [0.62412991, 0.69174945, 0.15683101, 0.13135137],
       [0.98596431, 0.76046633, 0.37250486, 0.2560899 ],
       [0.50296935, 0.78574223, 0.76119489, 0.57887849]])

_10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор._

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4))
matrix

array([[ 2,  2,  1,  4],
       [10,  1,  2,  1],
       [ 9,  1,  3,  1]])

In [31]:
vector= np.random.randint(1, 11, size=4)
vector

array([5, 6, 2, 9])

In [32]:
np.dot(matrix, vector)

array([60, 69, 66])

_11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор._

In [33]:
matrix = np.random.random((2, 3))
matrix

array([[0.63139188, 0.91110684, 0.24803655],
       [0.67020872, 0.89847993, 0.02960029]])

In [34]:
vector= np.random.random(3)
vector

array([0.12220126, 0.10250164, 0.7985101 ])

In [35]:
np.dot(matrix, vector)

array([0.36860651, 0.19763214])

_12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення._

In [36]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_1

array([[5, 3],
       [3, 9]])

In [37]:
matrix_2 = np.random.randint(1, 11, size=(2, 2))
matrix_2

array([[ 5,  6],
       [ 1, 10]])

In [38]:
matrix_1 * matrix_2

array([[25, 18],
       [ 3, 90]])

In [39]:
np.multiply(matrix_1, matrix_2)

array([[25, 18],
       [ 3, 90]])

_13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток._

In [40]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_1

array([[8, 7],
       [6, 9]])

In [41]:
matrix_2 = np.random.randint(1, 11, size=(2, 2))
matrix_2

array([[2, 7],
       [2, 6]])

In [42]:
np.dot(matrix_1, matrix_2)

array([[30, 98],
       [30, 96]])

_14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці._

In [43]:
matrix = np.random.randint(1, 101, size=(5, 5))
matrix

array([[67, 82, 50, 85, 10],
       [30, 37, 52, 99, 87],
       [60, 57, 63, 21, 39],
       [23, 36,  4, 51, 78],
       [61, 88, 77, 21, 80]])

In [44]:
np.sum(matrix)

1358

_15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю._

In [45]:
matrix_1 = np.random.randint(1, 11, size=(4, 4))
matrix_1

array([[ 7,  5,  9,  5],
       [ 9,  7, 10,  8],
       [ 1,  6,  2,  1],
       [ 8,  9,  4, 10]])

In [46]:
matrix_2 = np.random.randint(1, 11, size=(4, 4))
matrix_2

array([[10,  7, 10,  7],
       [ 8,  3, 10,  1],
       [ 6,  5,  7, 10],
       [ 4, 10,  3,  2]])

In [47]:
matrix_1 - matrix_2

array([[-3, -2, -1, -2],
       [ 1,  4,  0,  7],
       [-5,  1, -5, -9],
       [ 4, -1,  1,  8]])

_16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці._

In [48]:
matrix = np.random.random((3, 3))
matrix

array([[0.32625607, 0.5034324 , 0.95118963],
       [0.8245194 , 0.72308699, 0.3738302 ],
       [0.0588841 , 0.92291821, 0.86829557]])

In [49]:
sums = np.sum(matrix, axis=1)
sums

array([1.7808781 , 1.92143659, 1.85009788])

In [50]:
vector_column = sums.reshape(-1, 1)
vector_column

array([[1.7808781 ],
       [1.92143659],
       [1.85009788]])

_17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел._

In [51]:
matrix = np.random.randint(1, 11, size=(3, 4))
matrix

array([[10,  6,  8,  4],
       [ 5,  7,  2,  9],
       [ 4,  9,  3,  2]])

In [52]:
squared_matrix = np.square(matrix)
squared_matrix

array([[100,  36,  64,  16],
       [ 25,  49,   4,  81],
       [ 16,  81,   9,   4]])

_18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел._

In [53]:
arr = np.random.randint(1, 51, 4)
arr

array([ 9, 34, 29, 29])

In [54]:
sqrt_vector = np.sqrt(arr)
sqrt_vector

array([3.        , 5.83095189, 5.38516481, 5.38516481])