In [1]:
import numpy as np

_1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення._

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

_2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення._

In [4]:
matrix = np.zeros((3,3))

In [5]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

_3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення._

In [6]:
matrix = np.random.randint(1, 11, size=(5, 5))

In [7]:
matrix

array([[10,  4,  7,  3,  4],
       [ 1,  5,  2,  3,  3],
       [ 5,  5,  2, 10,  8],
       [ 3,  6,  1,  7,  4],
       [ 3,  2,  5,  3,  3]])

_4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення._

In [8]:
matrix = np.random.randint(2, size=(4, 4))

In [9]:
matrix

array([[0, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 0, 0]])

_5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення._

In [10]:
arr_1 = np.random.randint(1, 11, 5)
arr_2 = np.random.randint(1, 11, 5)

In [11]:
arr_1

array([9, 5, 9, 8, 6])

In [12]:
arr_2

array([7, 1, 8, 9, 1])

In [13]:
arr_1 + arr_2

array([16,  6, 17, 17,  7])

In [14]:
arr_1 - arr_2

array([ 2,  4,  1, -1,  5])

In [15]:
arr_1 * arr_2

array([63,  5, 72, 72,  6])

_6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток._

In [16]:
arr_1 = np.random.randint(1, 8, 7)
arr_2 = np.random.randint(1, 8, 7)

In [17]:
arr_1

array([6, 6, 4, 5, 1, 5, 1])

In [18]:
arr_2

array([2, 4, 3, 1, 5, 5, 2])

In [19]:
s_dot = np.dot(arr_1, arr_2)

In [20]:
s_dot

85

_7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою._

In [21]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 3))

In [22]:
matrix_1

array([[10,  8],
       [ 8, 10]])

In [23]:
matrix_2

array([[2, 9, 9],
       [7, 1, 6]])

In [24]:
np.dot(matrix_1, matrix_2)

array([[ 76,  98, 138],
       [ 86,  82, 132]])

_8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю._

In [25]:
matrix = np.random.randint(1, 11, size=(3, 3))
matrix

array([[ 8, 10,  7],
       [ 4,  6,  6],
       [ 2,  6,  8]])

In [26]:
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[-0.6,  1.9, -0.9],
       [ 1. , -2.5,  1. ],
       [-0.6,  1.4, -0.4]])

In [27]:
inverse_matrix = np.linalg.inv(inverse_matrix)
inverse_matrix

array([[ 8., 10.,  7.],
       [ 4.,  6.,  6.],
       [ 2.,  6.,  8.]])

_9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її._

In [28]:
matrix = np.random.random((4, 4))
matrix

array([[0.06041756, 0.57356303, 0.5139901 , 0.47371892],
       [0.34955012, 0.17108215, 0.27628875, 0.04250663],
       [0.7563789 , 0.33936974, 0.43610869, 0.76550192],
       [0.7973697 , 0.5471995 , 0.59671614, 0.69806741]])

In [29]:
transposed_matrix = np.transpose(matrix)
transposed_matrix

array([[0.06041756, 0.34955012, 0.7563789 , 0.7973697 ],
       [0.57356303, 0.17108215, 0.33936974, 0.5471995 ],
       [0.5139901 , 0.27628875, 0.43610869, 0.59671614],
       [0.47371892, 0.04250663, 0.76550192, 0.69806741]])

_10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор._

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4))
matrix

array([[ 2,  8, 10,  6],
       [ 5,  7,  9,  3],
       [ 9,  4,  9,  1]])

In [31]:
vector= np.random.randint(1, 11, size=4)
vector

array([ 9,  5, 10,  8])

In [32]:
np.dot(matrix, vector)

array([206, 194, 199])

_11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор._

In [33]:
matrix = np.random.random((2, 3))
matrix

array([[0.57118214, 0.8343502 , 0.99867554],
       [0.70237098, 0.49912497, 0.51606199]])

In [34]:
vector= np.random.random(3)
vector

array([0.42029423, 0.76989112, 0.27713147])

In [35]:
np.dot(matrix, vector)

array([1.15918779, 0.82249137])

_12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення._

In [36]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_1

array([[3, 6],
       [8, 3]])

In [37]:
matrix_2 = np.random.randint(1, 11, size=(2, 2))
matrix_2

array([[6, 3],
       [8, 9]])

In [38]:
matrix_1 * matrix_2

array([[18, 18],
       [64, 27]])

In [39]:
np.multiply(matrix_1, matrix_2)

array([[18, 18],
       [64, 27]])

_13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток._

In [40]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_1

array([[4, 6],
       [3, 5]])

In [41]:
matrix_2 = np.random.randint(1, 11, size=(2, 2))
matrix_2

array([[ 1, 10],
       [ 8,  5]])

In [42]:
np.dot(matrix_1, matrix_2)

array([[52, 70],
       [43, 55]])

_14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці._

In [43]:
matrix = np.random.randint(1, 101, size=(5, 5))
matrix

array([[20, 73, 95, 76, 42],
       [35, 32, 98, 80,  9],
       [27, 13, 41, 47, 87],
       [66, 20, 86, 67, 87],
       [47,  3, 43, 88,  6]])

In [44]:
np.sum(matrix)

1288

_15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю._

In [45]:
matrix_1 = np.random.randint(1, 11, size=(4, 4))
matrix_1

array([[ 2,  6,  2,  7],
       [ 5, 10,  2,  3],
       [10,  3,  9,  8],
       [ 9,  9,  8,  7]])

In [46]:
matrix_2 = np.random.randint(1, 11, size=(4, 4))
matrix_2

array([[ 1,  4,  5, 10],
       [10,  1,  4,  5],
       [ 8,  5,  8,  1],
       [ 2,  7,  5,  7]])

In [47]:
matrix_1 - matrix_2

array([[ 1,  2, -3, -3],
       [-5,  9, -2, -2],
       [ 2, -2,  1,  7],
       [ 7,  2,  3,  0]])

_16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці._

In [48]:
matrix = np.random.random((3, 3))
matrix

array([[0.84679902, 0.38238234, 0.17521434],
       [0.19410521, 0.35751705, 0.95877262],
       [0.27434391, 0.97967092, 0.60125374]])

In [49]:
sums = np.sum(matrix, axis=1)
sums

array([1.4043957 , 1.51039489, 1.85526858])

In [50]:
vector_column = sums.reshape(-1, 1)
vector_column

array([[1.4043957 ],
       [1.51039489],
       [1.85526858]])

_17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел._

In [51]:
matrix = np.random.randint(1, 11, size=(3, 4))
matrix

array([[ 2,  6,  8,  8],
       [ 1,  4,  2, 10],
       [10,  6,  5,  9]])

In [52]:
squared_matrix = np.square(matrix)
squared_matrix

array([[  4,  36,  64,  64],
       [  1,  16,   4, 100],
       [100,  36,  25,  81]])

_18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел._

In [53]:
arr = np.random.randint(1, 51, 4)
arr

array([25,  6, 50, 31])

In [54]:
sqrt_vector = np.sqrt(arr)
sqrt_vector

array([5.        , 2.44948974, 7.07106781, 5.56776436])