In [1]:
import numpy as np

_1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення._

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

_2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення._

In [4]:
matrix = np.zeros((3,3))

In [5]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

_3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення._

In [6]:
matrix = np.random.randint(1, 11, size=(5, 5))

In [7]:
matrix

array([[ 4,  2,  8, 10,  3],
       [ 2,  9,  8, 10,  8],
       [ 3,  3,  9,  2,  8],
       [ 7,  5,  2,  2,  2],
       [ 5,  8,  6, 10,  4]])

_4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення._

In [8]:
matrix = np.random.randint(2, size=(4, 4))

In [9]:
matrix

array([[1, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1]])

_5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення._

In [10]:
arr_1 = np.random.randint(1, 11, 5)
arr_2 = np.random.randint(1, 11, 5)

In [11]:
arr_1

array([2, 3, 2, 2, 3])

In [12]:
arr_2

array([ 4,  2,  7, 10,  5])

In [13]:
arr_1 + arr_2

array([ 6,  5,  9, 12,  8])

In [14]:
arr_1 - arr_2

array([-2,  1, -5, -8, -2])

In [15]:
arr_1 * arr_2

array([ 8,  6, 14, 20, 15])

_6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток._

In [16]:
arr_1 = np.random.randint(1, 8, 7)
arr_2 = np.random.randint(1, 8, 7)

In [17]:
arr_1

array([4, 2, 5, 4, 1, 6, 7])

In [18]:
arr_2

array([1, 3, 6, 6, 3, 3, 5])

In [19]:
s_dot = np.dot(arr_1, arr_2)

In [20]:
s_dot

120

_7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою._

In [21]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 3))

In [22]:
matrix_1

array([[6, 9],
       [3, 3]])

In [23]:
matrix_2

array([[8, 3, 1],
       [5, 8, 6]])

In [24]:
np.dot(matrix_1, matrix_2)

array([[93, 90, 60],
       [39, 33, 21]])

_8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю._

In [25]:
matrix = np.random.randint(1, 11, size=(3, 3))
matrix

array([[ 5,  3,  7],
       [ 4,  6,  6],
       [ 1, 10, 10]])

In [26]:
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[-4.44089210e-17,  2.94117647e-01, -1.76470588e-01],
       [-2.50000000e-01,  3.16176471e-01, -1.47058824e-02],
       [ 2.50000000e-01, -3.45588235e-01,  1.32352941e-01]])

In [27]:
inverse_matrix = np.linalg.inv(inverse_matrix)
inverse_matrix

array([[ 5.,  3.,  7.],
       [ 4.,  6.,  6.],
       [ 1., 10., 10.]])

_9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її._

In [28]:
matrix = np.random.random((4, 4))
matrix

array([[0.49756559, 0.02191919, 0.68708192, 0.41802737],
       [0.82889317, 0.16284009, 0.13925328, 0.15269471],
       [0.18524341, 0.7386229 , 0.60235385, 0.92152735],
       [0.11032487, 0.59806179, 0.83469891, 0.47845336]])

In [29]:
transposed_matrix = np.transpose(matrix)
transposed_matrix

array([[0.49756559, 0.82889317, 0.18524341, 0.11032487],
       [0.02191919, 0.16284009, 0.7386229 , 0.59806179],
       [0.68708192, 0.13925328, 0.60235385, 0.83469891],
       [0.41802737, 0.15269471, 0.92152735, 0.47845336]])

_10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор._

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4))
matrix

array([[ 9, 10,  1,  3],
       [ 3,  4,  2,  4],
       [ 4,  5,  8,  6]])

In [31]:
vector= np.random.randint(1, 11, size=4)
vector

array([2, 5, 8, 7])

In [32]:
np.dot(matrix, vector)

array([ 97,  70, 139])

_11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор._

In [33]:
matrix = np.random.random((2, 3))
matrix

array([[0.05980855, 0.70520576, 0.62527013],
       [0.36230609, 0.09025834, 0.63954987]])

In [34]:
vector= np.random.random(3)
vector

array([0.38923867, 0.43977601, 0.64208523])

In [35]:
np.dot(matrix, vector)

array([0.73488909, 0.59136253])

_12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення._

In [36]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_1

array([[ 2,  1],
       [ 4, 10]])

In [37]:
matrix_2 = np.random.randint(1, 11, size=(2, 2))
matrix_2

array([[10, 10],
       [ 3,  7]])

In [38]:
matrix_1 * matrix_2

array([[20, 10],
       [12, 70]])

In [39]:
np.multiply(matrix_1, matrix_2)

array([[20, 10],
       [12, 70]])

_13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток._

In [40]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_1

array([[ 6,  6],
       [10,  8]])

In [41]:
matrix_2 = np.random.randint(1, 11, size=(2, 2))
matrix_2

array([[9, 4],
       [5, 6]])

In [42]:
np.dot(matrix_1, matrix_2)

array([[ 84,  60],
       [130,  88]])

_14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці._

In [43]:
matrix = np.random.randint(1, 101, size=(5, 5))
matrix

array([[92, 58, 41, 45, 71],
       [ 4, 12, 85, 67, 43],
       [ 6, 54, 19, 97, 56],
       [65, 16, 14, 17, 76],
       [90, 98, 72,  7, 11]])

In [44]:
np.sum(matrix)

1216

_15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю._

In [45]:
matrix_1 = np.random.randint(1, 11, size=(4, 4))
matrix_1

array([[ 9,  7,  6,  4],
       [10,  2, 10,  4],
       [ 4,  5,  8,  6],
       [ 2, 10,  5,  4]])

In [46]:
matrix_2 = np.random.randint(1, 11, size=(4, 4))
matrix_2

array([[10,  9,  8,  8],
       [ 3,  1,  6,  2],
       [ 3,  8,  1,  6],
       [10,  8,  6,  3]])

In [47]:
matrix_1 - matrix_2

array([[-1, -2, -2, -4],
       [ 7,  1,  4,  2],
       [ 1, -3,  7,  0],
       [-8,  2, -1,  1]])

_16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці._

In [48]:
matrix = np.random.random((3, 3))
matrix

array([[0.71634741, 0.89356371, 0.40772264],
       [0.40485331, 0.9796772 , 0.23122693],
       [0.40124446, 0.47695179, 0.51587092]])

In [49]:
sums = np.sum(matrix, axis=1)
sums

array([2.01763377, 1.61575745, 1.39406717])

In [50]:
vector_column = sums.reshape(-1, 1)
vector_column

array([[2.01763377],
       [1.61575745],
       [1.39406717]])

_17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел._

In [51]:
matrix = np.random.randint(1, 11, size=(3, 4))
matrix

array([[5, 7, 8, 5],
       [4, 4, 5, 9],
       [3, 6, 7, 1]])

In [52]:
squared_matrix = np.square(matrix)
squared_matrix

array([[25, 49, 64, 25],
       [16, 16, 25, 81],
       [ 9, 36, 49,  1]])

_18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел._

In [53]:
arr = np.random.randint(1, 51, 4)
arr

array([14, 47, 13, 23])

In [54]:
sqrt_vector = np.sqrt(arr)
sqrt_vector

array([3.74165739, 6.8556546 , 3.60555128, 4.79583152])